services:
  # ---- PROMETHEUS ----
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/etc:/etc/prometheus
      - ./prometheus/data:/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
  # ---- GRAFANA ----
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    ports:
      - "3000:3000"
  # ---- ALERTMANAGER ----
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    command: --config.file=/config/alertmanager.yml --log.level=info
    volumes:
      - "./alertmanager/config:/config"
      - "./alertmanager/data:/data"
    restart: unless-stopped
    ports:
      - "9093:9093"
  # ---- SPEEDTEST EXPORTER ----
  speedtest-exporter:
    image: miguelndecarvalho/speedtest-exporter
    container_name: speedtest-exporter
    restart: unless-stopped
    ports:
      - 9798:9798
  # ---- NODE EXPORTER ----
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    pid: host
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.interrupts'
      - "--collector.tcpstat"
      - '--collector.processes'
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/host:ro,rslave'
      - '/run/udev:/run/udev:ro'
    restart: unless-stopped
    network_mode: host