services:
  trivy:
    image: amonacoos/trivy-with-docker:arm64
    container_name: trivy
    environment:
      - GOTIFY_ENDPOINT=<GOTIFY_IP>:8008
      - GOTIFY_TOKEN=<GOTIFY_TOKEN>
      - TELEGRAM_CHAT_ID=<TELEGRAM_CHAT_ID>
      - TELEGRAM_BOT_TOKEN=<TELEGRAM_BOT_TOKEN>
    entrypoint: /bin/sh
    command: >
      -c '
      mkdir -p /metrics;

      while true; do
        echo "Starting scan at:" $$(date);
        echo "" > /metrics/trivy.prom;
        ALERT=0;

        for image in $$(docker ps --format "{{.Image}}" | sort -u); do
          echo "Scanning image:" $$image;
          OUTPUT=$$(trivy image --format json --severity CRITICAL,HIGH $$image 2>/dev/null);
          echo "Raw OUTPUT: $$OUTPUT"
          VULN_COUNT=$$(echo "$$OUTPUT" | jq "[.Results[].Vulnerabilities? // [] | length] | add // 0");
          VULN_COUNT=$${VULN_COUNT:-0}
          echo "Vulnerabilities found: $$VULN_COUNT"
          echo "trivy_vulnerabilities{image=\"$$image\"} $$VULN_COUNT" >> /metrics/trivy.prom;
          if [ -n "$$VULN_COUNT" ] && [ "$$VULN_COUNT" -gt 0 ]; then
            ALERT=1;
          fi;
        done;

        if [ "$$ALERT" = "1" ]; then
          # Gotify alert
          curl -s -X POST "$${GOTIFY_ENDPOINT}?token=$${GOTIFY_TOKEN}" \
            -F "title=Trivy Alert" \
            -F "message=🦠 One or more container images have critical/high vulnerabilities." \
            -F "priority=5";

          # Telegram alert
          curl -s -X POST "https://api.telegram.org/bot$${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="$${TELEGRAM_CHAT_ID}" \
            -d text="🦠 *Trivy Alert*: One or more container images have critical/high vulnerabilities." \
            -d parse_mode=Markdown;
        fi;

        echo "Scan complete, sleeping 24 hours seconds...";
        sleep 86400;
      done
      '
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./trivy-cache:/root/.cache/trivy
      - ./metrics:/metrics
    restart: unless-stopped

  trivy-metrics-server:
    image: nginx:alpine
    container_name: trivy-metrics-server
    volumes:
      - ./metrics:/usr/share/nginx/html:ro
    ports:
      - "8085:80"
    restart: unless-stopped
