services:
  # ---- PORTAINER ----
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: 'Europe/Madrid'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    restart: unless-stopped
    ports:
      - 9000:9000
